### ISSUE TITLE
Use development/production NODE_ENV 

### ISSUE THREAD

**Issue by helb** [raymestalez/django-react-blog#4]
I get this warning on digitalmind.io (both Chrome and FF):

![magpie_20170314_155423](https://cloud.githubusercontent.com/assets/178133/23906522/802b6322-08ce-11e7-8c74-66d72f63795d.png)

There are probably two problems:
- the live site runs with development build, not [production one](https://webpack.js.org/guides/production-build/) (`webpack -p`)
- as the warning says, the code shouldn't be minified when running in development mode

I use something like this to minify code only in production builds:

```javascript
function getPlugins() {
    const plugins = [];

    if (process.env.NODE_ENV === "production") {
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            minimize: true,
            output: {
                comments: false
            },
            compressor: {
                warnings: false
            }
        }));
    } else {
        // not related to this issue,
        // but quite useful, too :)
        plugins.push(new webpack.HotModuleReplacementPlugin());
    }

    return plugins;
}

module.exports = {
    …
    plugins: getPlugins(),
    …
}
```

**Comment by lumenwrites** [comment]
Oh, this is awesome! To be honest, I don't entirely understand how webpack works yet, but I've added your code and the error is gone =)

Thank you very much for your help!
